spring.application.name=BackEnd3NA

spring.datasource.url=jdbc:postgresql://localhost:5432/AppAlarme
spring.datasource.username=postgres
spring.datasource.password=729500

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect